### ISSUE TITLE
How do I change the font in the end?

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [NMSCD/No-Mans-Sky-Universal-Font#2]
?

**Comment by Khaoz-Topsy** [comment]
Hi, can you be a bit more specific? 
If you want to edit the font, all the files are in the [assets > fonts folder](https://github.com/NMSCD/No-Mans-Sky-Universal-Font/tree/master/assets/font), I am not sure about what you mean "in the end" 😅

**Comment by subsubsubsubsubsub** [comment]
how to change in game already have FuturaProBook Version

**Comment by Khaoz-Topsy** [comment]
Oh ok! Sorry this is not something that we have documentation on. You would need to create a mod that overwrites the font files used in the game with these fonts. The goal of this repo is to make the font available for people to use in their projects
